# demo02_矩阵.ipynb  矩阵

In [1]:
import numpy as np

In [4]:
ary = np.array([[1,2,3], [4,5,6], [7,8,9]])
m = np.mat(ary)
print(m, type(m))

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.matrix'>


In [6]:
print(ary * ary)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [5]:
print(m * m)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [7]:
m2 = np.mat('1 2 3; 4 5 6')
print(m2)

[[1 2 3]
 [4 5 6]]


## 矩阵乘法规则

In [10]:
m

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
m * m

matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

## 逆矩阵

In [14]:
m = np.mat('1 2 6; 2 5 9; 4 5 8')
print(m)
print(m.I)
print(m * m.I)

[[1 2 6]
 [2 5 9]
 [4 5 8]]
[[ 0.2  -0.56  0.48]
 [-0.8   0.64 -0.12]
 [ 0.4  -0.12 -0.04]]
[[ 1.00000000e+00  5.55111512e-17 -2.77555756e-17]
 [-3.33066907e-16  1.00000000e+00 -6.93889390e-17]
 [ 0.00000000e+00  2.22044605e-16  1.00000000e+00]]


## 解线性方程组

In [18]:
A = np.mat('3 3.2; 3.5 3.6')
B = np.mat('118.4; 135.2')
x = A.I * B
x
# 使用linalg.lstsq() 方法求 x
x = np.linalg.lstsq(A, B)[0]
x

<ipython-input-18-c89b10dc86ab>:6: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x = np.linalg.lstsq(A, B)[0]


matrix([[16.],
        [22.]])

In [31]:
n = 38

# 使用递归实现斐波那契数列
def fibo(n):
    return 1 if n < 3 else fibo(n - 1) + fibo(n - 2)
print(fibo(n))

39088169


In [32]:
F = np.mat('1 1; 1 0')
F = F.astype('int64')
F**38

matrix([[63245986, 39088169],
        [39088169, 24157817]], dtype=int64)